# Generated by Django 4.2.16 on 2025-04-09 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stu_main', '0004_alter_subject_code'),
        ('exams', '0002_remove_exam_end_time_remove_exam_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='assigned_class',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='assigned_class',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='teacher',
        ),
        migrations.AddField(
            model_name='assignment',
            name='class_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='stu_main.classsubject'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='class_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='stu_main.classsubject'),
        ),
        migrations.AddField(
            model_name='exam',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentassignmentrecord',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_records', to='exams.assignment'),
        ),
        migrations.AlterField(
            model_name='studentassignmentrecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_records', to='stu_main.student'),
        ),
        migrations.AlterField(
            model_name='studentexamrecord',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_records', to='exams.exam'),
        ),
        migrations.AlterField(
            model_name='studentexamrecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_records', to='stu_main.student'),
        ),
    ]
