# Generated by Django 4.2.16 on 2025-04-09 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_alter_studentassignmentrecord_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='title',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='title',
        ),
    ]
