# Generated by Django 4.2.16 on 2025-04-10 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
        ('exams', '0005_remove_assignment_title_remove_exam_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentassignmentrecord',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='studentassignmentrecord',
            name='student',
        ),
        migrations.AlterField(
            model_name='question',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assignments.assignment'),
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.DeleteModel(
            name='StudentAssignmentRecord',
        ),
    ]
