# Generated by Django 5.1.7 on 2025-03-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpost',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='disliked_posts', to='stu_main.student'),
        ),
    ]
