# Generated by Django 4.2.16 on 2025-04-09 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stu_main', '0004_alter_subject_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsubject',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='stu_main.class'),
        ),
    ]
